[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "laforge-test"
version = "0.1.0"
description = "A utility for managing Units and dependencies in a project with artifact registry"
readme = "README.md"
requires-python = ">=3.7"
authors = [
    {name = "Tom Yedwab", email = "sincerelyyourstom@gmail.com"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

[project.scripts]
laforge-test = "laforge_test.main:main"

[tool.setuptools]
packages = ["laforge_test"]
