FROM debian:bookworm-slim

# Install packages and clean up temporary files
RUN apt update && apt install -y curl zip && apt clean && rm -rf /var/lib/apt/lists/*

# Create a non-root user and group
RUN adduser --disabled-password --gecos "" opencode
RUN mkdir -p /home/opencode/.config/opencode /home/opencode/.local/share/opencode /src
RUN chown -R opencode:opencode /home/opencode

# Switch to the non-root user
USER opencode
WORKDIR /home/opencode

# Install opencode
RUN curl -fsSL https://opencode.ai/install | bash

WORKDIR /src

ENTRYPOINT ["/home/opencode/.opencode/bin/opencode"]
